/**
 * Zero-dependency app store built on useSyncExternalStore.
 *
 * Hydration is synchronous from local storage, so the first frame already shows real data.
 * Writes go to storage first, then notify subscribers. No network here.
 */
import { useSyncExternalStore } from 'react';

import { alertsRepo, cacheMetaRepo, draftsRepo, feedRepo, initStorage, myReportsRepo, onStorageNotice, prefsRepo, resetAll, sessionRepo, settingsRepo, storageNoticeRepo, type MyReportLink } from '@/data/repos';
import { nowIso, setClockOffset } from '@/domain/time';
import type { AlertItem, AuthSession, CacheMetaMap, Draft, LocationFix, Prefs, PublicReport, Settings, StorageNotice } from '@/domain/types';

export interface NetworkInfo {
  /** true = online, false = offline, null = not determined yet. */
  online: boolean | null;
  type: string | null;
}

export interface AppState {
  hydrated: boolean;
  onboarded: boolean;
  prefs: Prefs;
  settings: Settings;
  session: AuthSession | null;
  /** Cached public reports around the home area (re-downloadable). */
  feed: PublicReport[];
  /** Reports generated by the active demo scenario (never persisted; regenerated at boot). */
  demoReports: PublicReport[];
  drafts: Draft[];
  alerts: AlertItem[];
  myReports: MyReportLink[];
  cacheMeta: CacheMetaMap;
  network: NetworkInfo;
  location: LocationFix | null;
  locationStatus: 'idle' | 'requesting' | 'granted' | 'denied' | 'unavailable';
  lastRefreshAt: number | null;
  refreshing: boolean;
  refreshProgress: { done: number; total: number } | null;
  storageNotice: StorageNotice | null;
}

type Listener = () => void;

let state: AppState = {
  hydrated: false,
  onboarded: false,
  prefs: prefsRepo.get(),
  settings: settingsRepo.get(),
  session: null,
  feed: [],
  demoReports: [],
  drafts: [],
  alerts: [],
  myReports: [],
  cacheMeta: {},
  network: { online: null, type: null },
  location: null,
  locationStatus: 'idle',
  lastRefreshAt: null,
  refreshing: false,
  refreshProgress: null,
  storageNotice: null,
};

const listeners = new Set<Listener>();

function emit() {
  for (const l of listeners) l();
}

export function setState(patch: Partial<AppState> | ((prev: AppState) => Partial<AppState>)) {
  const p = typeof patch === 'function' ? patch(state) : patch;
  state = { ...state, ...p };
  emit();
}

export function getState(): AppState {
  return state;
}

export function subscribe(l: Listener): () => void {
  listeners.add(l);
  return () => listeners.delete(l);
}

/** Synchronous hydration from disk. Safe to call more than once. */
export function hydrate(): AppState {
  initStorage();
  const settings = settingsRepo.get();
  setClockOffset(settings.demoClockOffsetMs);
  state = {
    ...state,
    hydrated: true,
    onboarded: prefsRepo.isOnboarded(),
    prefs: prefsRepo.get(),
    settings,
    session: sessionRepo.get(),
    feed: feedRepo.get(),
    drafts: draftsRepo.getAll(),
    alerts: alertsRepo.getAll(),
    myReports: myReportsRepo.getAll(),
    cacheMeta: cacheMetaRepo.getAll(),
    storageNotice: storageNoticeRepo.get(),
  };
  emit();
  return state;
}

onStorageNotice((notice) => {
  setState({ storageNotice: notice, feed: feedRepo.get(), alerts: alertsRepo.getAll(), drafts: draftsRepo.getAll(), cacheMeta: cacheMetaRepo.getAll() });
});

// ---------- Selectors / hooks ----------

export function useAppState<T>(selector: (s: AppState) => T): T {
  return useSyncExternalStore(subscribe, () => selector(state), () => selector(state));
}

export function useAppStore(): AppState {
  return useSyncExternalStore(subscribe, getState, getState);
}

// ---------- Actions (local-first: disk first, then state) ----------

export const actions = {
  savePrefs(p: Prefs, opts: { finishOnboarding?: boolean } = {}) {
    const clean = prefsRepo.set({ ...p, updatedAt: nowIso() });
    if (opts.finishOnboarding) prefsRepo.setOnboarded(true);
    setState({ prefs: clean, onboarded: opts.finishOnboarding ? true : state.onboarded });
    return clean;
  },
  skipOnboarding() {
    prefsRepo.setOnboarded(true);
    setState({ onboarded: true });
  },
  patchSettings(p: Partial<Settings>) {
    const next = settingsRepo.patch(p);
    setClockOffset(next.demoClockOffsetMs);
    setState({ settings: next });
    return next;
  },
  setSession(s: AuthSession | null) {
    sessionRepo.set(s);
    setState({ session: s });
  },
  setFeed(reports: PublicReport[]) {
    feedRepo.set(reports);
    setState({ feed: feedRepo.get() });
  },
  upsertReport(report: PublicReport) {
    setState({ feed: feedRepo.upsert(report) });
  },
  setDemoReports(reports: PublicReport[]) {
    setState({ demoReports: reports });
  },
  upsertDraft(d: Draft) {
    setState({ drafts: draftsRepo.upsert(d) });
  },
  removeDraft(id: string) {
    setState({ drafts: draftsRepo.remove(id) });
  },
  setDraftStatus(id: string, status: Draft['status'], extra: Partial<Pick<Draft, 'failReason' | 'reportId'>> = {}) {
    setState({ drafts: draftsRepo.setStatus(id, status, extra) });
  },
  addMyReport(link: MyReportLink) {
    setState({ myReports: myReportsRepo.add(link) });
  },
  setAlerts(items: AlertItem[]) {
    alertsRepo.set(items);
    setState({ alerts: alertsRepo.getAll() });
  },
  markAlertRead(id: string) {
    setState({ alerts: alertsRepo.markRead(id) });
  },
  setCacheMeta(meta: CacheMetaMap) {
    setState({ cacheMeta: meta });
  },
  setNetwork(n: NetworkInfo) {
    setState({ network: n });
  },
  /** The fix lives in memory only: it is used for sorting and drafting, then forgotten with the process. */
  setLocation(fix: LocationFix | null, status: AppState['locationStatus']) {
    setState({ location: fix ?? state.location, locationStatus: status });
  },
  setRefreshing(refreshing: boolean, lastRefreshAt?: number) {
    setState({ refreshing, ...(refreshing ? {} : { refreshProgress: null }), ...(lastRefreshAt !== undefined ? { lastRefreshAt } : {}) });
  },
  setRefreshProgress(done: number, total: number) {
    setState({ refreshProgress: { done, total } });
  },
  dismissStorageNotice() {
    storageNoticeRepo.clear();
    setState({ storageNotice: null });
  },
  rehydrate() {
    hydrate();
  },
  /** Offline data → Reset this phone. */
  resetAll() {
    resetAll();
    setClockOffset(0);
    state = { ...state, onboarded: false, prefs: prefsRepo.get(), settings: settingsRepo.get(), session: null, feed: [], demoReports: [], drafts: [], alerts: [], myReports: [], cacheMeta: {}, storageNotice: null, lastRefreshAt: null };
    emit();
  },
};

/** Effective "offline" flag: real network state, or the demo override. */
export function isOfflineNow(s: AppState = state): boolean {
  if (s.settings.simulateOffline) return true;
  return s.network.online === false;
}
